services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:BWuPvCdtBVWmxkORUboDs4CoKJAkmr2K0cW+zWKA9Ec=
      - key: DB_HOST
        value: YOUR_DB_HOST  # Replace with the database host
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: laravel_project
      - key: DB_USERNAME
        value: mydb
      - key: DB_PASSWORD
        value: mydb@2630
